module DpdGeoApi
  class Response
    attr_reader http_status: Integer
    attr_reader body: Hash[Symbol, untyped]
    attr_reader errors: Array[untyped]

    def initialize: (Integer, ?String) -> void
    def response_code: -> Integer?
    def response_message: -> String?
    def response_description: -> String?
    def valid?: -> bool

    private

    def parse_body: (String) -> Hash[Symbol, untyped]
  end
end
